CREATE TABLE "PROJECTUSER"."DATASETMASTER"
  (
    "DATASETID"    NUMBER NOT NULL ENABLE,
    "DATASETNAME"  VARCHAR2(250) NOT NULL ENABLE,
    "CREATEDBY"    VARCHAR2(40) NOT NULL ENABLE,
    "UPDATEDBY"    VARCHAR2(40) NOT NULL ENABLE,
    "CREATIONDATE" TIMESTAMP NOT NULL ENABLE,
    "UPDATEDATE"   TIMESTAMP NOT NULL ENABLE,
    "STATUS"       VARCHAR2(20) NOT NULL ENABLE,
    CONSTRAINT "DATASET_PK" PRIMARY KEY ("DATASETID")
  );
CREATE TABLE "PROJECTUSER"."DATASETHISTORY"
  (
    "DATASETHISTORYID" NUMBER NOT NULL ENABLE,
    "DATASETID"        NUMBER NOT NULL ENABLE,
    "DATASETNAME"      VARCHAR2(250) NOT NULL ENABLE,
    "CREATEDBY"        VARCHAR2(40) NOT NULL ENABLE,
    "UPDATEDBY"        VARCHAR2(40) NOT NULL ENABLE,
    "CREATIONDATE"     TIMESTAMP NOT NULL ENABLE,
    "UPDATEDATE"       TIMESTAMP NOT NULL ENABLE,
    CONSTRAINT "DATASETHISTORY_PK" PRIMARY KEY ("DATASETHISTORYID"),
    CONSTRAINT "DATASETHISTORY_FK2" FOREIGN KEY ("DATASETID") REFERENCES "PROJECTUSER"."DATASETMASTER" ("DATASETID") ENABLE
  ) ;
CREATE TABLE "PROJECTUSER"."DATASETRUN"
  (
    "DATASETRUNID"       NUMBER NOT NULL ENABLE,
    "PARENTDATASETRUNID" NUMBER NOT NULL ENABLE,
    "DATASETID"          NUMBER NOT NULL ENABLE,
    "RUNBY"              VARCHAR2(40) NOT NULL ENABLE,
    "RUNTIME"            TIMESTAMP (6) NOT NULL ENABLE,
    "RUNSTATUS"          VARCHAR2(20) NOT NULL ENABLE,
    "RUNPHASE"           VARCHAR2(20) NOT NULL ENABLE,
    "READYFORRUN"        CHAR(2) NOT NULL ENABLE,
    CONSTRAINT "DATASETRUN_PK" PRIMARY KEY ("DATASETRUNID"),
    CONSTRAINT "DATASETRUN_FK1" FOREIGN KEY ("DATASETID") REFERENCES "PROJECTUSER"."DATASETMASTER" ("DATASETID") ENABLE
  ) ;
-------------------------------------------------------- feature tables -----------------------------------------------
CREATE TABLE "PROJECTUSER"."FEATUREMASTER"
  (
    "FEATUREID"                 NUMBER NOT NULL ENABLE,
    "FEATURESET"                VARCHAR2(20) NOT NULL ENABLE,
    "CREATEDBY"                 VARCHAR2(40) NOT NULL ENABLE,
    "UPDATEDBY"                 VARCHAR2(40) NOT NULL ENABLE,
    "CREATIONDATE"              TIMESTAMP NOT NULL ENABLE,
    "UPDATEDATE"                TIMESTAMP NOT NULL ENABLE,
    "STATUS"                    VARCHAR2(20) NOT NULL ENABLE,
    "BA"                        VARCHAR2(255) NULL,
    "FEATUREDATASETCATAGOERY"   VARCHAR2(255) NULL,
    "FEATUREGROUPING"           VARCHAR2(255) NULL,
    "FEATUREOWNER"              VARCHAR2(255) NULL,
    "FEATUREROLLOUT"            VARCHAR2(1) NULL,
    "FEATURESTATUS"             VARCHAR2(255) NULL,
	"FEATUREPHASE"             VARCHAR2(255) NULL,
    "FEATURETESTEXECUTIONPHASE" VARCHAR2(255) NULL,
    "FEATURETESTSCRIPTCOMMENTS" VARCHAR2(4000) NULL,
    "FEATURETESTSCRIPTNAME"     VARCHAR2(4000) NULL,
    "OWNER"                     VARCHAR2(255) NULL,
    "RECORDSTATUS"              NUMBER(10) NULL,
    CONSTRAINT "FEATUREMASTER_PK" PRIMARY KEY ("FEATUREID")
  );
CREATE TABLE "PROJECTUSER"."DATASETFEATUREHISTORY"
  (
    "FEATUREHISTORYID"          NUMBER NOT NULL ENABLE,
    "FEATURESET"                VARCHAR2(20) NOT NULL ENABLE,
    "DATASETID"                 NUMBER NOT NULL ENABLE,
    "FEATUREMASTERID"           NUMBER NOT NULL ENABLE,
    "CREATEDBY"                 VARCHAR2(40) NOT NULL ENABLE,
    "UPDATEDBY"                 VARCHAR2(40) NOT NULL ENABLE,
    "CREATIONDATE"              TIMESTAMP NOT NULL ENABLE,
    "UPDATEDATE"                TIMESTAMP NOT NULL ENABLE,
    "BA"                        VARCHAR2(255) NULL,
    "FEATUREDATASETCATAGOERY"   VARCHAR2(255) NULL,
    "FEATUREGROUPING"           VARCHAR2(255) NULL,
    "FEATUREOWNER"              VARCHAR2(255) NULL,
    "FEATUREROLLOUT"            VARCHAR2(1) NULL,
    "FEATURESTATUS"             VARCHAR2(255) NULL,
	"FEATUREPHASE"             VARCHAR2(255) NULL,
    "FEATURETESTEXECUTIONPHASE" VARCHAR2(255) NULL,
    "FEATURETESTSCRIPTCOMMENTS" VARCHAR2(4000) NULL,
    "FEATURETESTSCRIPTNAME"     VARCHAR2(4000) NULL,
    "OWNER"                     VARCHAR2(255) NULL,
    "RECORDSTATUS"              NUMBER(10) NULL,
    CONSTRAINT "FEATUREHISTORY_PK" PRIMARY KEY ("FEATUREHISTORYID") ENABLE ,
    CONSTRAINT "FEATUREHISTORY_FK1" FOREIGN KEY ("DATASETID") REFERENCES "PROJECTUSER"."DATASETMASTER" ("DATASETID") ENABLE ,
    CONSTRAINT "FEATUREHISTORY_FK2" FOREIGN KEY ("FEATUREMASTERID") REFERENCES "PROJECTUSER"."FEATUREMASTER" ("FEATUREID") ENABLE
  );
CREATE TABLE "PROJECTUSER"."DATASETFEATURE"
  (
    "FEATUREID" NUMBER NOT NULL ENABLE,
    "DATASETID" NUMBER NOT NULL ENABLE,
    CONSTRAINT "FEATURE_FK1" FOREIGN KEY ("DATASETID") REFERENCES "PROJECTUSER"."DATASETMASTER" ("DATASETID") ENABLE,
    CONSTRAINT "FEATURE_FK2" FOREIGN KEY ("FEATUREID") REFERENCES "PROJECTUSER"."FEATUREMASTER" ("FEATUREID") ENABLE
  ) ;
CREATE TABLE "PROJECTUSER"."FEATURERUN"
  (
    "FEATURERUNID"    NUMBER NOT NULL ENABLE,
    "FEATUREMASTERID" NUMBER NOT NULL ENABLE,
    "DATASETRUNID"    NUMBER NOT NULL ENABLE,
    "STATUS"          VARCHAR2(20) NOT NULL ENABLE,
    CONSTRAINT "FEATURERUN_PK" PRIMARY KEY ("FEATURERUNID") ENABLE,
    CONSTRAINT "FEATURERUN_FK1" FOREIGN KEY ("DATASETRUNID") REFERENCES "PROJECTUSER"."DATASETRUN" ("DATASETRUNID") ENABLE ,
    CONSTRAINT "FEATURERUN_FK2" FOREIGN KEY ("FEATUREMASTERID") REFERENCES "PROJECTUSER"."FEATUREMASTER" ("FEATUREID") ENABLE
  ) ;
-------------------------------------------------------- Accounts tables -----------------------------------------------------------
CREATE TABLE "PROJECTUSER"."ACCOUNTMASTER"
  (
    "ACCOUNTID"    NUMBER NOT NULL ENABLE,
    "ACCOUNTNAME"  VARCHAR2(200) NOT NULL ENABLE,
    "ACCOUNTSETID" NUMBER NOT NULL ENABLE,
    "CREATEDBY"    VARCHAR2(40) NOT NULL ENABLE,
    "UPDATEDBY"    VARCHAR2(40) NOT NULL ENABLE,
    "CREATIONDATE" TIMESTAMP NOT NULL ENABLE,
    "UPDATEDATE"   TIMESTAMP NOT NULL ENABLE,
    "STATUS"       VARCHAR2(20) NOT NULL ENABLE,
    CONSTRAINT "ACCOUNTMASTER_PK" PRIMARY KEY ("ACCOUNTID") ENABLE
  );
CREATE TABLE "PROJECTUSER"."DATASETACCOUNTHISTORY"
  (
    "ACCOUNTHISTORYID" NUMBER NOT NULL ENABLE,
    "DATASETMASTERID"  NUMBER NOT NULL ENABLE,
    "ACCOUNTMASTERID"  NUMBER NOT NULL ENABLE,
    "CREATEDBY"        VARCHAR2(40) NOT NULL ENABLE,
    "UPDATEDBY"        VARCHAR2(40) NOT NULL ENABLE,
    "CREATIONDATE"     TIMESTAMP NOT NULL ENABLE,
    "UPDATEDATE"       TIMESTAMP NOT NULL ENABLE,
    CONSTRAINT "ACCOUNTHISTORY_PK" PRIMARY KEY ("ACCOUNTHISTORYID") ENABLE,
    CONSTRAINT "ACCOUNTHISTORY_FK1" FOREIGN KEY ("DATASETMASTERID") REFERENCES "PROJECTUSER"."DATASETMASTER" ("DATASETID") ENABLE ,
    CONSTRAINT "ACCOUNTHISTORY_FK2" FOREIGN KEY ("ACCOUNTMASTERID") REFERENCES "PROJECTUSER"."ACCOUNTMASTER" ("ACCOUNTID") ENABLE
  ) ;
CREATE TABLE "PROJECTUSER"."DATASETACCOUNT"
  (
    "ACCOUNTMASTERID" NUMBER,
    "DATASETMASTERID" NUMBER NOT NULL ENABLE,
    CONSTRAINT "ACCOUNT_FK2" FOREIGN KEY ("DATASETMASTERID") REFERENCES "PROJECTUSER"."DATASETMASTER" ("DATASETID") ENABLE,
    CONSTRAINT "ACCOUNT_FK1" FOREIGN KEY ("ACCOUNTMASTERID") REFERENCES "PROJECTUSER"."ACCOUNTMASTER" ("ACCOUNTID") ENABLE
  ) ;
CREATE TABLE "PROJECTUSER"."ACCOUNTRUN"
  (
    "ACCOUNTRUNID"    NUMBER NOT NULL ENABLE,
    "ACCOUNTMASTERID" NUMBER NOT NULL ENABLE,
    "DATASETRUNID"    NUMBER NOT NULL ENABLE,
    CONSTRAINT "ACCOUNTRUN_PK" PRIMARY KEY ("ACCOUNTRUNID") ENABLE,
    CONSTRAINT "ACCOUNTRUN_FK1" FOREIGN KEY ("DATASETRUNID") REFERENCES "PROJECTUSER"."DATASETRUN" ("DATASETRUNID") ENABLE,
    CONSTRAINT "ACCOUNTRUN_FK2" FOREIGN KEY ("ACCOUNTMASTERID") REFERENCES "PROJECTUSER"."ACCOUNTMASTER" ("ACCOUNTID") ENABLE
  );
---------------------------------------------------------------------- DEFECTS ---------------------------------------------------------------
CREATE TABLE "PROJECTUSER"."DATASETRUNDEFECT"
  (
    "RUNDEFECTID"   NUMBER NOT NULL ENABLE,
    "DATASETRUNID"  NUMBER NOT NULL ENABLE,
    "FEATURERUNID"  NUMBER ,
    "HPQCDEFECTID"  NUMBER NOT NULL ENABLE,
    "DEFECTSTATUS"  VARCHAR2(20) NOT NULL ENABLE,
    "DEFECTSEVRITY" VARCHAR2(20) NOT NULL ENABLE,
    CONSTRAINT "DATASETRUNDEFECT_PK" PRIMARY KEY ("RUNDEFECTID" ,"DATASETRUNID") ENABLE,
    CONSTRAINT "DATASETRUNDEFECT_FK1" FOREIGN KEY ("FEATURERUNID") REFERENCES "PROJECTUSER"."FEATURERUN" ("FEATURERUNID") ,
    CONSTRAINT "DATASETRUNDEFECT_FK2" FOREIGN KEY ("DATASETRUNID") REFERENCES "PROJECTUSER"."DATASETRUN" ("DATASETRUNID") ENABLE
  ) ;
CREATE TABLE "PROJECTUSER"."USERDETAILS"
  (
    "USER_ID"      NUMBER(10) NOT NULL,
    "ACCESSLEVEL"  VARCHAR2(255) NULL,
    "EMPID"        VARCHAR2(255) NULL,
    "PASSWORD"     VARCHAR2(255) NULL,
    "USERNAME"     VARCHAR2(255) NULL,
    "CREATEDBY"        VARCHAR2(40) NOT NULL ENABLE,
    "UPDATEDBY"        VARCHAR2(40) NOT NULL ENABLE,
    "CREATIONDATE"     TIMESTAMP NOT NULL ENABLE,
    "UPDATEDATE"       TIMESTAMP NOT NULL ENABLE,
    CONSTRAINT "USERDETAILS_PK" PRIMARY KEY ("USER_ID") ENABLE
  ); 
  
  
  CREATE TABLE "PROJECTUSER"."MASTERDATA"
  (
    "ID"         NUMBER(10) NOT NULL, 
    "CATAGORY"     VARCHAR(255),
    "CATDATA"      VARCHAR(255),
    "CREATEDBY"        VARCHAR2(40) NOT NULL ENABLE,
    "UPDATEDBY"        VARCHAR2(40) NOT NULL ENABLE,
    "CREATIONDATE"     TIMESTAMP NOT NULL ENABLE,
    "UPDATEDATE"       TIMESTAMP NOT NULL ENABLE,
    CONSTRAINT "MASTERDATA_PK" PRIMARY KEY ("ID") ENABLE 
  );