--<ScriptOptions statementTerminator=";"/>

ALTER TABLE "PROJECTUSER"."ACCOUNTHISTORY" DROP CONSTRAINT "ACCOUNTHISTORY_FK1";

ALTER TABLE "PROJECTUSER"."ACCOUNTHISTORY" DROP CONSTRAINT "ACCOUNTHISTORY_PK";

DROP INDEX "PROJECTUSER"."ACCOUNTHISTORY_PK";

DROP TABLE "PROJECTUSER"."ACCOUNTHISTORY";

CREATE TABLE "PROJECTUSER"."ACCOUNTHISTORY" (
		"ACCOUNTHISTORYID" NUMBER(22 , 0) NOT NULL,
		"DATASETID" NUMBER(22 , 0) NOT NULL,
		"ACCOUNTMASTERID" NUMBER(22 , 0) NOT NULL,
		"CREATEDBY" VARCHAR2(40) NOT NULL,
		"UPDATEDBY" VARCHAR2(40) NOT NULL,
		"CREATIONDATE" DATE NOT NULL,
		"UPDATEDATE" DATE NOT NULL
	);

CREATE UNIQUE INDEX "PROJECTUSER"."ACCOUNTHISTORY_PK" ON "PROJECTUSER"."ACCOUNTHISTORY" ("ACCOUNTHISTORYID" ASC);

ALTER TABLE "PROJECTUSER"."ACCOUNTHISTORY" ADD CONSTRAINT "ACCOUNTHISTORY_PK" PRIMARY KEY ("ACCOUNTHISTORYID");

ALTER TABLE "PROJECTUSER"."ACCOUNTHISTORY" ADD CONSTRAINT "ACCOUNTHISTORY_FK1" FOREIGN KEY ("DATASETID")
	REFERENCES "PROJECTUSER"."DATASET" ("DSETID")
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

